# Pytorch References

In [1]:
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader, TensorDataset
import numpy as np
import matplotlib.pyplot as plt

print("PyTorch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
print("MPS available:", hasattr(torch.backends, "mps") and torch.backends.mps.is_available())

if torch.cuda.is_available():
    device = torch.device("cuda")
elif hasattr(torch.backends, "mps") and torch.backends.mps.is_available():
    device = torch.device("mps")
else:
    device = torch.device("cpu")

print("Using device:", device)

PyTorch version: 2.10.0
CUDA available: False
MPS available: True
Using device: mps


In [2]:
# Tensors

scalar = torch.tensor(5)
vector = torch.tensor([1, 2, 3])
matrix = torch.tensor([[1, 2], [3, 4]])
tensor3d = torch.tensor([[[1], [2]], [[3], [4]]])

print("scalar:", scalar)
print("vector:", vector)
print("matrix:\n", matrix)
print("tensor3d:\n", tensor3d)

scalar: tensor(5)
vector: tensor([1, 2, 3])
matrix:
 tensor([[1, 2],
        [3, 4]])
tensor3d:
 tensor([[[1],
         [2]],

        [[3],
         [4]]])


In [3]:
# Tensor Properies

x = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])

print("Tensor:\n", x)
print("shape:", x.shape)
print("ndim:", x.ndim)
print("dtype:", x.dtype)
print("device:", x.device)
print("numel:", x.numel())
print("size():", x.size())

Tensor:
 tensor([[1., 2., 3.],
        [4., 5., 6.]])
shape: torch.Size([2, 3])
ndim: 2
dtype: torch.float32
device: cpu
numel: 6
size(): torch.Size([2, 3])


In [4]:
# Creating tensors

zeros = torch.zeros((2, 3))
ones = torch.ones((2, 3))
full = torch.full((2, 3), 7)
eye = torch.eye(3)
arange_tensor = torch.arange(0, 10, 2)
linspace_tensor = torch.linspace(0, 1, 5)
rand_tensor = torch.rand((2, 3))
randn_tensor = torch.randn((2, 3))
randint_tensor = torch.randint(0, 10, (2, 3))

print("zeros:\n", zeros)
print("\nones:\n", ones)
print("\nfull:\n", full)
print("\neye:\n", eye)
print("\narange:", arange_tensor)
print("linspace:", linspace_tensor)
print("\nrand:\n", rand_tensor)
print("\nrandn:\n", randn_tensor)
print("\nrandint:\n", randint_tensor)

zeros:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])

ones:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])

full:
 tensor([[7, 7, 7],
        [7, 7, 7]])

eye:
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

arange: tensor([0, 2, 4, 6, 8])
linspace: tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])

rand:
 tensor([[0.7012, 0.2791, 0.4189],
        [0.4596, 0.6511, 0.4628]])

randn:
 tensor([[ 1.4700, -0.7435, -0.8188],
        [-1.1716, -0.8102, -0.6366]])

randint:
 tensor([[9, 2, 3],
        [7, 9, 0]])


In [5]:
# Dtypes and casting

x = torch.tensor([1, 2, 3], dtype=torch.int32)
y = x.float()
z = x.to(torch.float64)

print("Original:", x, x.dtype)
print("float():", y, y.dtype)
print("to(torch.float64):", z, z.dtype)


Original: tensor([1, 2, 3], dtype=torch.int32) torch.int32
float(): tensor([1., 2., 3.]) torch.float32
to(torch.float64): tensor([1., 2., 3.], dtype=torch.float64) torch.float64


In [6]:
# NumPy Conversion

x = torch.tensor([1.0, 2.0, 3.0])
x_np = x.numpy()

print("Torch tensor:", x)
print("NumPy array:", x_np)

back_to_torch = torch.from_numpy(x_np)
print("Back to torch:", back_to_torch)

Torch tensor: tensor([1., 2., 3.])
NumPy array: [1. 2. 3.]
Back to torch: tensor([1., 2., 3.])


In [7]:
# Tensor Indexing and Slicing

x = torch.arange(1, 13).reshape(3, 4)

print("x:\n", x)
print("\nFirst row:", x[0])
print("Element at row 2, col 3:", x[1, 2])
print("Last column:", x[:, -1])
print("First two rows:\n", x[:2])
print("Submatrix:\n", x[1:, 1:3])

x:
 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

First row: tensor([1, 2, 3, 4])
Element at row 2, col 3: tensor(7)
Last column: tensor([ 4,  8, 12])
First two rows:
 tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
Submatrix:
 tensor([[ 6,  7],
        [10, 11]])


In [8]:
# Reshaping, transpose, squeeze, unsqueeze

x = torch.arange(12)

reshaped = x.reshape(3, 4)
viewed = x.view(3, 4)
transposed = reshaped.T
flattened = reshaped.flatten()
unsqueezed = x.unsqueeze(0)
squeezed = torch.tensor([[[1], [2], [3]]]).squeeze()

print("Original:", x)
print("\nreshape:\n", reshaped)
print("\nview:\n", viewed)
print("\ntranspose:\n", transposed)
print("\nflatten:", flattened)
print("\nunsqueeze shape:", unsqueezed.shape)
print("squeeze:", squeezed)


Original: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

reshape:
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

view:
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

transpose:
 tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])

flatten: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

unsqueeze shape: torch.Size([1, 12])
squeeze: tensor([1, 2, 3])


In [9]:
# Concatentation and stacking

a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])

print("cat dim=0:\n", torch.cat([a, b], dim=0))
print("\ncat dim=1:\n", torch.cat([a, b], dim=1))
print("\nstack dim=0:\n", torch.stack([a, b], dim=0))
print("\nstack dim=1:\n", torch.stack([a, b], dim=1))


cat dim=0:
 tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

cat dim=1:
 tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

stack dim=0:
 tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

stack dim=1:
 tensor([[[1, 2],
         [5, 6]],

        [[3, 4],
         [7, 8]]])


In [10]:
# Math operations

a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([10.0, 20.0, 30.0])

print("a + b =", a + b)
print("a - b =", a - b)
print("a * b =", a * b)
print("b / a =", b / a)
print("torch.add:", torch.add(a, b))
print("torch.square:", torch.square(a))
print("torch.sqrt:", torch.sqrt(b))
print("torch.exp:", torch.exp(a))
print("torch.log:", torch.log(a))
print("torch.sin:", torch.sin(a))
print("torch.cos:", torch.cos(a))

a + b = tensor([11., 22., 33.])
a - b = tensor([ -9., -18., -27.])
a * b = tensor([10., 40., 90.])
b / a = tensor([10., 10., 10.])
torch.add: tensor([11., 22., 33.])
torch.square: tensor([1., 4., 9.])
torch.sqrt: tensor([3.1623, 4.4721, 5.4772])
torch.exp: tensor([ 2.7183,  7.3891, 20.0855])
torch.log: tensor([0.0000, 0.6931, 1.0986])
torch.sin: tensor([0.8415, 0.9093, 0.1411])
torch.cos: tensor([ 0.5403, -0.4161, -0.9900])


In [11]:
# Reductions and Statistics

x = torch.tensor([[1.0, 2.0], [3.0, 4.0]])

print("sum:", torch.sum(x))
print("mean:", torch.mean(x))
print("max:", torch.max(x))
print("min:", torch.min(x))
print("argmax:", torch.argmax(x))
print("argmin:", torch.argmin(x))
print("sum dim=0:", torch.sum(x, dim=0))
print("mean dim=1:", torch.mean(x, dim=1))
print("std:", torch.std(x))

sum: tensor(10.)
mean: tensor(2.5000)
max: tensor(4.)
min: tensor(1.)
argmax: tensor(3)
argmin: tensor(0)
sum dim=0: tensor([4., 6.])
mean dim=1: tensor([1.5000, 3.5000])
std: tensor(1.2910)


In [12]:
# Matrix Mult. and Linear Alg.

A = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
B = torch.tensor([[5.0, 6.0], [7.0, 8.0]])
v = torch.tensor([1.0, 2.0])

print("matmul:\n", torch.matmul(A, B))
print("\nA @ B:\n", A @ B)
print("\ndot:", torch.dot(v, v))
print("\ntranspose A:\n", A.T)
print("\ndeterminant:", torch.linalg.det(A))
print("\ninverse:\n", torch.linalg.inv(A))
print("\nnorm:", torch.linalg.norm(v))

matmul:
 tensor([[19., 22.],
        [43., 50.]])

A @ B:
 tensor([[19., 22.],
        [43., 50.]])

dot: tensor(5.)

transpose A:
 tensor([[1., 3.],
        [2., 4.]])

determinant: tensor(-2.)

inverse:
 tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]])

norm: tensor(2.2361)


In [13]:
# Broadcasting

matrix = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
vector = torch.tensor([10.0, 20.0, 30.0])

print("Matrix:\n", matrix)
print("\nVector:", vector)
print("\nBroadcasted result:\n", matrix + vector)

Matrix:
 tensor([[1., 2., 3.],
        [4., 5., 6.]])

Vector: tensor([10., 20., 30.])

Broadcasted result:
 tensor([[11., 22., 33.],
        [14., 25., 36.]])


In [14]:
# Devicces - CPU, CUDA, MPS

x = torch.tensor([1.0, 2.0, 3.0])

x_on_device = x.to(device)
print("Original device:", x.device)
print("Moved device:", x_on_device.device)

# Move back to CPU if needed
x_cpu = x_on_device.cpu()
print("Back to CPU:", x_cpu.device)

Original device: cpu
Moved device: mps:0
Back to CPU: cpu


In [15]:
# Autogradient

x = torch.tensor(3.0, requires_grad=True)
y = x**2 + 2*x + 1

y.backward()

print("y =", y.item())
print("dy/dx =", x.grad.item())

y = 16.0
dy/dx = 8.0


In [16]:
# Multivariable gradients

w = torch.tensor(2.0, requires_grad=True)
b = torch.tensor(1.0, requires_grad=True)
x = torch.tensor(3.0)

y = w * x + b
loss = (y - 10.0) ** 2
loss.backward()

print("loss:", loss.item())
print("dw:", w.grad.item())
print("db:", b.grad.item())


loss: 9.0
dw: -18.0
db: -6.0


In [17]:
# remove grad
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)

with torch.no_grad():
    y = x * 2

print("Requires grad for x:", x.requires_grad)
print("Requires grad for y:", y.requires_grad)

Requires grad for x: True
Requires grad for y: False


In [33]:
# Dataset loading
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

iris = load_iris()

print(iris.data.shape)

X = iris.data.astype(np.float32)
y = iris.target.astype(np.int64)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("Classes:", iris.target_names)

(150, 4)
X_train shape: (120, 4)
X_test shape: (30, 4)
Classes: ['setosa' 'versicolor' 'virginica']


In [34]:
# TensorDataset and DataLoader

X_train_tensor = torch.tensor(X_train)
y_train_tensor = torch.tensor(y_train)
X_test_tensor = torch.tensor(X_test)
y_test_tensor = torch.tensor(y_test)

train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
test_dataset = TensorDataset(X_test_tensor, y_test_tensor)

train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=16, shuffle=True)

for xb, yb in train_loader:
    print("Batch X shape:", xb.shape)
    print("Batch y shape:", yb.shape)
    break

Batch X shape: torch.Size([16, 4])
Batch y shape: torch.Size([16])


In [ ]:
# Building a model with torch.nn.Module

class IrisClassifier(nn.MOdule)